# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: urlmap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='urlmap.proto',
  package='urlmap',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0curlmap.proto\x12\x06urlmap\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0cRedirectPath\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tnotify_to\x18\x02 \x01(\t\"(\n\x06OrgUrl\x12\x0b\n\x03org\x18\x01 \x01(\t\x12\x11\n\tnotify_to\x18\x02 \x01(\t\"\'\n\x04User\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x11\n\tnotify_to\x18\x02 \x01(\t\"<\n\x11\x41rrayRedirectData\x12\'\n\tredirects\x18\x01 \x03(\x0b\x32\x14.urlmap.RedirectData\"_\n\x0cRedirectData\x12&\n\x08redirect\x18\x01 \x01(\x0b\x32\x14.urlmap.RedirectInfo\x1a\'\n\tValidDate\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\"n\n\x0cRedirectInfo\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x14\n\x0credirectPath\x18\x02 \x01(\t\x12\x0b\n\x03org\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x0f\n\x07\x63omment\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x05\x32\x89\x02\n\x0bRedirection\x12\x34\n\x0cGetOrgByPath\x12\x14.urlmap.RedirectPath\x1a\x0e.urlmap.OrgUrl\x12\x38\n\rGetInfoByUser\x12\x0c.urlmap.User\x1a\x19.urlmap.ArrayRedirectData\x12/\n\x07SetInfo\x12\x14.urlmap.RedirectData\x1a\x0e.urlmap.OrgUrl\x12%\n\x07SetUser\x12\x0c.urlmap.User\x1a\x0c.urlmap.User\x12\x32\n\nRemoveUser\x12\x0c.urlmap.User\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_REDIRECTPATH = _descriptor.Descriptor(
  name='RedirectPath',
  full_name='urlmap.RedirectPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='urlmap.RedirectPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_to', full_name='urlmap.RedirectPath.notify_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=100,
)


_ORGURL = _descriptor.Descriptor(
  name='OrgUrl',
  full_name='urlmap.OrgUrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='org', full_name='urlmap.OrgUrl.org', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_to', full_name='urlmap.OrgUrl.notify_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=142,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='urlmap.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='urlmap.User.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_to', full_name='urlmap.User.notify_to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=183,
)


_ARRAYREDIRECTDATA = _descriptor.Descriptor(
  name='ArrayRedirectData',
  full_name='urlmap.ArrayRedirectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='redirects', full_name='urlmap.ArrayRedirectData.redirects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=245,
)


_REDIRECTDATA_VALIDDATE = _descriptor.Descriptor(
  name='ValidDate',
  full_name='urlmap.RedirectData.ValidDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin', full_name='urlmap.RedirectData.ValidDate.begin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='urlmap.RedirectData.ValidDate.end', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=342,
)

_REDIRECTDATA = _descriptor.Descriptor(
  name='RedirectData',
  full_name='urlmap.RedirectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='redirect', full_name='urlmap.RedirectData.redirect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REDIRECTDATA_VALIDDATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=342,
)


_REDIRECTINFO = _descriptor.Descriptor(
  name='RedirectInfo',
  full_name='urlmap.RedirectInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='urlmap.RedirectInfo.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redirectPath', full_name='urlmap.RedirectInfo.redirectPath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org', full_name='urlmap.RedirectInfo.org', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='urlmap.RedirectInfo.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='urlmap.RedirectInfo.comment', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active', full_name='urlmap.RedirectInfo.active', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=454,
)

_ARRAYREDIRECTDATA.fields_by_name['redirects'].message_type = _REDIRECTDATA
_REDIRECTDATA_VALIDDATE.containing_type = _REDIRECTDATA
_REDIRECTDATA.fields_by_name['redirect'].message_type = _REDIRECTINFO
DESCRIPTOR.message_types_by_name['RedirectPath'] = _REDIRECTPATH
DESCRIPTOR.message_types_by_name['OrgUrl'] = _ORGURL
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['ArrayRedirectData'] = _ARRAYREDIRECTDATA
DESCRIPTOR.message_types_by_name['RedirectData'] = _REDIRECTDATA
DESCRIPTOR.message_types_by_name['RedirectInfo'] = _REDIRECTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedirectPath = _reflection.GeneratedProtocolMessageType('RedirectPath', (_message.Message,), {
  'DESCRIPTOR' : _REDIRECTPATH,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.RedirectPath)
  })
_sym_db.RegisterMessage(RedirectPath)

OrgUrl = _reflection.GeneratedProtocolMessageType('OrgUrl', (_message.Message,), {
  'DESCRIPTOR' : _ORGURL,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.OrgUrl)
  })
_sym_db.RegisterMessage(OrgUrl)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.User)
  })
_sym_db.RegisterMessage(User)

ArrayRedirectData = _reflection.GeneratedProtocolMessageType('ArrayRedirectData', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYREDIRECTDATA,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.ArrayRedirectData)
  })
_sym_db.RegisterMessage(ArrayRedirectData)

RedirectData = _reflection.GeneratedProtocolMessageType('RedirectData', (_message.Message,), {

  'ValidDate' : _reflection.GeneratedProtocolMessageType('ValidDate', (_message.Message,), {
    'DESCRIPTOR' : _REDIRECTDATA_VALIDDATE,
    '__module__' : 'urlmap_pb2'
    # @@protoc_insertion_point(class_scope:urlmap.RedirectData.ValidDate)
    })
  ,
  'DESCRIPTOR' : _REDIRECTDATA,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.RedirectData)
  })
_sym_db.RegisterMessage(RedirectData)
_sym_db.RegisterMessage(RedirectData.ValidDate)

RedirectInfo = _reflection.GeneratedProtocolMessageType('RedirectInfo', (_message.Message,), {
  'DESCRIPTOR' : _REDIRECTINFO,
  '__module__' : 'urlmap_pb2'
  # @@protoc_insertion_point(class_scope:urlmap.RedirectInfo)
  })
_sym_db.RegisterMessage(RedirectInfo)



_REDIRECTION = _descriptor.ServiceDescriptor(
  name='Redirection',
  full_name='urlmap.Redirection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=457,
  serialized_end=722,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrgByPath',
    full_name='urlmap.Redirection.GetOrgByPath',
    index=0,
    containing_service=None,
    input_type=_REDIRECTPATH,
    output_type=_ORGURL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetInfoByUser',
    full_name='urlmap.Redirection.GetInfoByUser',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_ARRAYREDIRECTDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetInfo',
    full_name='urlmap.Redirection.SetInfo',
    index=2,
    containing_service=None,
    input_type=_REDIRECTDATA,
    output_type=_ORGURL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetUser',
    full_name='urlmap.Redirection.SetUser',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_USER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveUser',
    full_name='urlmap.Redirection.RemoveUser',
    index=4,
    containing_service=None,
    input_type=_USER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDIRECTION)

DESCRIPTOR.services_by_name['Redirection'] = _REDIRECTION

# @@protoc_insertion_point(module_scope)
