# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import urlmap_pb2 as urlmap__pb2


class RedirectionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOrgByPath = channel.unary_unary(
        '/urlmap.Redirection/GetOrgByPath',
        request_serializer=urlmap__pb2.RedirectPath.SerializeToString,
        response_deserializer=urlmap__pb2.OrgUrl.FromString,
        )
    self.GetInfoByUser = channel.unary_unary(
        '/urlmap.Redirection/GetInfoByUser',
        request_serializer=urlmap__pb2.User.SerializeToString,
        response_deserializer=urlmap__pb2.ArrayRedirectData.FromString,
        )
    self.SetInfo = channel.unary_unary(
        '/urlmap.Redirection/SetInfo',
        request_serializer=urlmap__pb2.RedirectData.SerializeToString,
        response_deserializer=urlmap__pb2.OrgUrl.FromString,
        )
    self.SetUser = channel.unary_unary(
        '/urlmap.Redirection/SetUser',
        request_serializer=urlmap__pb2.User.SerializeToString,
        response_deserializer=urlmap__pb2.User.FromString,
        )
    self.RemoveUser = channel.unary_unary(
        '/urlmap.Redirection/RemoveUser',
        request_serializer=urlmap__pb2.User.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class RedirectionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOrgByPath(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInfoByUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RedirectionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOrgByPath': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrgByPath,
          request_deserializer=urlmap__pb2.RedirectPath.FromString,
          response_serializer=urlmap__pb2.OrgUrl.SerializeToString,
      ),
      'GetInfoByUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetInfoByUser,
          request_deserializer=urlmap__pb2.User.FromString,
          response_serializer=urlmap__pb2.ArrayRedirectData.SerializeToString,
      ),
      'SetInfo': grpc.unary_unary_rpc_method_handler(
          servicer.SetInfo,
          request_deserializer=urlmap__pb2.RedirectData.FromString,
          response_serializer=urlmap__pb2.OrgUrl.SerializeToString,
      ),
      'SetUser': grpc.unary_unary_rpc_method_handler(
          servicer.SetUser,
          request_deserializer=urlmap__pb2.User.FromString,
          response_serializer=urlmap__pb2.User.SerializeToString,
      ),
      'RemoveUser': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveUser,
          request_deserializer=urlmap__pb2.User.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'urlmap.Redirection', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
